export const ApiActionTypes = {

    /* SEND_REQUEST: 'SEND_REQUEST', */
    REQUEST_SENT: 'REQUEST_SENT',
    SUCCESS_RESPONSE_RECEIVED: 'SUCCESS_RESPONSE_RECEIVED',
    FAIL_RESPONSE_RECEIVED: 'FAIL_RESPONSE_RECEIVED'
}